//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.20 at 01:49:56 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.glo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.factorialsystems.msscprovider.wsdl.glo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceCurrency_QNAME = new QName("http://com.guide/soap/server", "currency");
    private final static QName _RequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceValue_QNAME = new QName("http://com.guide/soap/server", "value");
    private final static QName _RequestTopupResponseReturnSenderPrincipalPrincipalId_QNAME = new QName("http://com.guide/soap/server", "principalId");
    private final static QName _RequestTopupResponseReturnSenderPrincipalPrincipalName_QNAME = new QName("http://com.guide/soap/server", "principalName");
    private final static QName _RequestTopupResponseReturnSenderPrincipalAccounts_QNAME = new QName("http://com.guide/soap/server", "accounts");
    private final static QName _RequestTopupResponseReturnSenderPrincipalStatus_QNAME = new QName("http://com.guide/soap/server", "status");
    private final static QName _RequestTopupResponseReturnSenderPrincipalMsisdn_QNAME = new QName("http://com.guide/soap/server", "msisdn");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.factorialsystems.msscprovider.wsdl.glo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestTopup }
     * 
     */
    public RequestTopup createRequestTopup() {
        return new RequestTopup();
    }

    /**
     * Create an instance of {@link RequestTopupResponse }
     * 
     */
    public RequestTopupResponse createRequestTopupResponse() {
        return new RequestTopupResponse();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return }
     * 
     */
    public RequestTopupResponse.Return createRequestTopupResponseReturn() {
        return new RequestTopupResponse.Return();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupPrincipal }
     * 
     */
    public RequestTopupResponse.Return.TopupPrincipal createRequestTopupResponseReturnTopupPrincipal() {
        return new RequestTopupResponse.Return.TopupPrincipal();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupPrincipal.Accounts }
     * 
     */
    public RequestTopupResponse.Return.TopupPrincipal.Accounts createRequestTopupResponseReturnTopupPrincipalAccounts() {
        return new RequestTopupResponse.Return.TopupPrincipal.Accounts();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupPrincipal.Accounts.Account }
     * 
     */
    public RequestTopupResponse.Return.TopupPrincipal.Accounts.Account createRequestTopupResponseReturnTopupPrincipalAccountsAccount() {
        return new RequestTopupResponse.Return.TopupPrincipal.Accounts.Account();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.SenderPrincipal }
     * 
     */
    public RequestTopupResponse.Return.SenderPrincipal createRequestTopupResponseReturnSenderPrincipal() {
        return new RequestTopupResponse.Return.SenderPrincipal();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.SenderPrincipal.Accounts }
     * 
     */
    public RequestTopupResponse.Return.SenderPrincipal.Accounts createRequestTopupResponseReturnSenderPrincipalAccounts() {
        return new RequestTopupResponse.Return.SenderPrincipal.Accounts();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.SenderPrincipal.Accounts.Account }
     * 
     */
    public RequestTopupResponse.Return.SenderPrincipal.Accounts.Account createRequestTopupResponseReturnSenderPrincipalAccountsAccount() {
        return new RequestTopupResponse.Return.SenderPrincipal.Accounts.Account();
    }

    /**
     * Create an instance of {@link RequestTopup.Context }
     * 
     */
    public RequestTopup.Context createRequestTopupContext() {
        return new RequestTopup.Context();
    }

    /**
     * Create an instance of {@link RequestTopup.SenderPrincipalId }
     * 
     */
    public RequestTopup.SenderPrincipalId createRequestTopupSenderPrincipalId() {
        return new RequestTopup.SenderPrincipalId();
    }

    /**
     * Create an instance of {@link RequestTopup.TopupPrincipalId }
     * 
     */
    public RequestTopup.TopupPrincipalId createRequestTopupTopupPrincipalId() {
        return new RequestTopup.TopupPrincipalId();
    }

    /**
     * Create an instance of {@link RequestTopup.SenderAccountSpecifier }
     * 
     */
    public RequestTopup.SenderAccountSpecifier createRequestTopupSenderAccountSpecifier() {
        return new RequestTopup.SenderAccountSpecifier();
    }

    /**
     * Create an instance of {@link RequestTopup.TopupAccountSpecifier }
     * 
     */
    public RequestTopup.TopupAccountSpecifier createRequestTopupTopupAccountSpecifier() {
        return new RequestTopup.TopupAccountSpecifier();
    }

    /**
     * Create an instance of {@link RequestTopup.Amount }
     * 
     */
    public RequestTopup.Amount createRequestTopupAmount() {
        return new RequestTopup.Amount();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.RequestedTopupAmount }
     * 
     */
    public RequestTopupResponse.Return.RequestedTopupAmount createRequestTopupResponseReturnRequestedTopupAmount() {
        return new RequestTopupResponse.Return.RequestedTopupAmount();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupAccountSpecifier }
     * 
     */
    public RequestTopupResponse.Return.TopupAccountSpecifier createRequestTopupResponseReturnTopupAccountSpecifier() {
        return new RequestTopupResponse.Return.TopupAccountSpecifier();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupAmount }
     * 
     */
    public RequestTopupResponse.Return.TopupAmount createRequestTopupResponseReturnTopupAmount() {
        return new RequestTopupResponse.Return.TopupAmount();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupPrincipal.PrincipalId }
     * 
     */
    public RequestTopupResponse.Return.TopupPrincipal.PrincipalId createRequestTopupResponseReturnTopupPrincipalPrincipalId() {
        return new RequestTopupResponse.Return.TopupPrincipal.PrincipalId();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.AccountSpecifier }
     * 
     */
    public RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.AccountSpecifier createRequestTopupResponseReturnTopupPrincipalAccountsAccountAccountSpecifier() {
        return new RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.AccountSpecifier();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.Balance }
     * 
     */
    public RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.Balance createRequestTopupResponseReturnTopupPrincipalAccountsAccountBalance() {
        return new RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.Balance();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.CreditLimit }
     * 
     */
    public RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.CreditLimit createRequestTopupResponseReturnTopupPrincipalAccountsAccountCreditLimit() {
        return new RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.CreditLimit();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.SenderPrincipal.PrincipalId }
     * 
     */
    public RequestTopupResponse.Return.SenderPrincipal.PrincipalId createRequestTopupResponseReturnSenderPrincipalPrincipalId() {
        return new RequestTopupResponse.Return.SenderPrincipal.PrincipalId();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.AccountSpecifier }
     * 
     */
    public RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.AccountSpecifier createRequestTopupResponseReturnSenderPrincipalAccountsAccountAccountSpecifier() {
        return new RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.AccountSpecifier();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.Balance }
     * 
     */
    public RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.Balance createRequestTopupResponseReturnSenderPrincipalAccountsAccountBalance() {
        return new RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.Balance();
    }

    /**
     * Create an instance of {@link RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.CreditLimit }
     * 
     */
    public RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.CreditLimit createRequestTopupResponseReturnSenderPrincipalAccountsAccountCreditLimit() {
        return new RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.CreditLimit();
    }

    /**
     * Create an instance of {@link RequestTopup.Context.InitiatorPrincipalId }
     * 
     */
    public RequestTopup.Context.InitiatorPrincipalId createRequestTopupContextInitiatorPrincipalId() {
        return new RequestTopup.Context.InitiatorPrincipalId();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "currency", scope = RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.Balance.class)
    public JAXBElement<String> createRequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceCurrency(String value) {
        return new JAXBElement<String>(_RequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceCurrency_QNAME, String.class, RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.Balance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "value", scope = RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.Balance.class)
    public JAXBElement<String> createRequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceValue(String value) {
        return new JAXBElement<String>(_RequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceValue_QNAME, String.class, RequestTopupResponse.Return.TopupPrincipal.Accounts.Account.Balance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestTopupResponse.Return.SenderPrincipal.PrincipalId }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestTopupResponse.Return.SenderPrincipal.PrincipalId }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "principalId", scope = RequestTopupResponse.Return.SenderPrincipal.class)
    public JAXBElement<RequestTopupResponse.Return.SenderPrincipal.PrincipalId> createRequestTopupResponseReturnSenderPrincipalPrincipalId(RequestTopupResponse.Return.SenderPrincipal.PrincipalId value) {
        return new JAXBElement<RequestTopupResponse.Return.SenderPrincipal.PrincipalId>(_RequestTopupResponseReturnSenderPrincipalPrincipalId_QNAME, RequestTopupResponse.Return.SenderPrincipal.PrincipalId.class, RequestTopupResponse.Return.SenderPrincipal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "principalName", scope = RequestTopupResponse.Return.SenderPrincipal.class)
    public JAXBElement<String> createRequestTopupResponseReturnSenderPrincipalPrincipalName(String value) {
        return new JAXBElement<String>(_RequestTopupResponseReturnSenderPrincipalPrincipalName_QNAME, String.class, RequestTopupResponse.Return.SenderPrincipal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestTopupResponse.Return.SenderPrincipal.Accounts }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestTopupResponse.Return.SenderPrincipal.Accounts }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "accounts", scope = RequestTopupResponse.Return.SenderPrincipal.class)
    public JAXBElement<RequestTopupResponse.Return.SenderPrincipal.Accounts> createRequestTopupResponseReturnSenderPrincipalAccounts(RequestTopupResponse.Return.SenderPrincipal.Accounts value) {
        return new JAXBElement<RequestTopupResponse.Return.SenderPrincipal.Accounts>(_RequestTopupResponseReturnSenderPrincipalAccounts_QNAME, RequestTopupResponse.Return.SenderPrincipal.Accounts.class, RequestTopupResponse.Return.SenderPrincipal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "status", scope = RequestTopupResponse.Return.SenderPrincipal.class)
    public JAXBElement<String> createRequestTopupResponseReturnSenderPrincipalStatus(String value) {
        return new JAXBElement<String>(_RequestTopupResponseReturnSenderPrincipalStatus_QNAME, String.class, RequestTopupResponse.Return.SenderPrincipal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "msisdn", scope = RequestTopupResponse.Return.SenderPrincipal.class)
    public JAXBElement<String> createRequestTopupResponseReturnSenderPrincipalMsisdn(String value) {
        return new JAXBElement<String>(_RequestTopupResponseReturnSenderPrincipalMsisdn_QNAME, String.class, RequestTopupResponse.Return.SenderPrincipal.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "currency", scope = RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.Balance.class)
    public JAXBElement<String> createRequestTopupResponseReturnSenderPrincipalAccountsAccountBalanceCurrency(String value) {
        return new JAXBElement<String>(_RequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceCurrency_QNAME, String.class, RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.Balance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.guide/soap/server", name = "value", scope = RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.Balance.class)
    public JAXBElement<String> createRequestTopupResponseReturnSenderPrincipalAccountsAccountBalanceValue(String value) {
        return new JAXBElement<String>(_RequestTopupResponseReturnTopupPrincipalAccountsAccountBalanceValue_QNAME, String.class, RequestTopupResponse.Return.SenderPrincipal.Accounts.Account.Balance.class, value);
    }

}
