//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.20 at 01:49:56 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.glo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="context"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="clientComment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="clientReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="clientRequestTimeout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="initiatorPrincipalId"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="senderPrincipalId"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="topupPrincipalId"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="senderAccountSpecifier"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="accountTypeId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="topupAccountSpecifier"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="accountTypeId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="amount"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "context",
    "senderPrincipalId",
    "topupPrincipalId",
    "senderAccountSpecifier",
    "topupAccountSpecifier",
    "productId",
    "amount"
})
@XmlRootElement(name = "requestTopup")
public class RequestTopup {

    @XmlElement(required = true)
    protected RequestTopup.Context context;
    @XmlElement(required = true)
    protected RequestTopup.SenderPrincipalId senderPrincipalId;
    @XmlElement(required = true)
    protected RequestTopup.TopupPrincipalId topupPrincipalId;
    @XmlElement(required = true)
    protected RequestTopup.SenderAccountSpecifier senderAccountSpecifier;
    @XmlElement(required = true)
    protected RequestTopup.TopupAccountSpecifier topupAccountSpecifier;
    @XmlElement(required = true)
    protected String productId;
    @XmlElement(required = true)
    protected RequestTopup.Amount amount;

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link RequestTopup.Context }
     *     
     */
    public RequestTopup.Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTopup.Context }
     *     
     */
    public void setContext(RequestTopup.Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the senderPrincipalId property.
     * 
     * @return
     *     possible object is
     *     {@link RequestTopup.SenderPrincipalId }
     *     
     */
    public RequestTopup.SenderPrincipalId getSenderPrincipalId() {
        return senderPrincipalId;
    }

    /**
     * Sets the value of the senderPrincipalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTopup.SenderPrincipalId }
     *     
     */
    public void setSenderPrincipalId(RequestTopup.SenderPrincipalId value) {
        this.senderPrincipalId = value;
    }

    /**
     * Gets the value of the topupPrincipalId property.
     * 
     * @return
     *     possible object is
     *     {@link RequestTopup.TopupPrincipalId }
     *     
     */
    public RequestTopup.TopupPrincipalId getTopupPrincipalId() {
        return topupPrincipalId;
    }

    /**
     * Sets the value of the topupPrincipalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTopup.TopupPrincipalId }
     *     
     */
    public void setTopupPrincipalId(RequestTopup.TopupPrincipalId value) {
        this.topupPrincipalId = value;
    }

    /**
     * Gets the value of the senderAccountSpecifier property.
     * 
     * @return
     *     possible object is
     *     {@link RequestTopup.SenderAccountSpecifier }
     *     
     */
    public RequestTopup.SenderAccountSpecifier getSenderAccountSpecifier() {
        return senderAccountSpecifier;
    }

    /**
     * Sets the value of the senderAccountSpecifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTopup.SenderAccountSpecifier }
     *     
     */
    public void setSenderAccountSpecifier(RequestTopup.SenderAccountSpecifier value) {
        this.senderAccountSpecifier = value;
    }

    /**
     * Gets the value of the topupAccountSpecifier property.
     * 
     * @return
     *     possible object is
     *     {@link RequestTopup.TopupAccountSpecifier }
     *     
     */
    public RequestTopup.TopupAccountSpecifier getTopupAccountSpecifier() {
        return topupAccountSpecifier;
    }

    /**
     * Sets the value of the topupAccountSpecifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTopup.TopupAccountSpecifier }
     *     
     */
    public void setTopupAccountSpecifier(RequestTopup.TopupAccountSpecifier value) {
        this.topupAccountSpecifier = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link RequestTopup.Amount }
     *     
     */
    public RequestTopup.Amount getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestTopup.Amount }
     *     
     */
    public void setAmount(RequestTopup.Amount value) {
        this.amount = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currency",
        "value"
    })
    public static class Amount {

        @XmlElement(required = true)
        protected String currency;
        @XmlElement(required = true)
        protected String value;

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="clientComment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="clientReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="clientRequestTimeout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="initiatorPrincipalId"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "channel",
        "clientComment",
        "clientId",
        "clientReference",
        "clientRequestTimeout",
        "initiatorPrincipalId",
        "password"
    })
    public static class Context {

        @XmlElement(required = true)
        protected String channel;
        @XmlElement(required = true)
        protected String clientComment;
        @XmlElement(required = true)
        protected String clientId;
        @XmlElement(required = true)
        protected String clientReference;
        @XmlElement(required = true)
        protected String clientRequestTimeout;
        @XmlElement(required = true)
        protected RequestTopup.Context.InitiatorPrincipalId initiatorPrincipalId;
        @XmlElement(required = true)
        protected String password;

        /**
         * Gets the value of the channel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChannel() {
            return channel;
        }

        /**
         * Sets the value of the channel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChannel(String value) {
            this.channel = value;
        }

        /**
         * Gets the value of the clientComment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientComment() {
            return clientComment;
        }

        /**
         * Sets the value of the clientComment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientComment(String value) {
            this.clientComment = value;
        }

        /**
         * Gets the value of the clientId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientId() {
            return clientId;
        }

        /**
         * Sets the value of the clientId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientId(String value) {
            this.clientId = value;
        }

        /**
         * Gets the value of the clientReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientReference() {
            return clientReference;
        }

        /**
         * Sets the value of the clientReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientReference(String value) {
            this.clientReference = value;
        }

        /**
         * Gets the value of the clientRequestTimeout property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientRequestTimeout() {
            return clientRequestTimeout;
        }

        /**
         * Sets the value of the clientRequestTimeout property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientRequestTimeout(String value) {
            this.clientRequestTimeout = value;
        }

        /**
         * Gets the value of the initiatorPrincipalId property.
         * 
         * @return
         *     possible object is
         *     {@link RequestTopup.Context.InitiatorPrincipalId }
         *     
         */
        public RequestTopup.Context.InitiatorPrincipalId getInitiatorPrincipalId() {
            return initiatorPrincipalId;
        }

        /**
         * Sets the value of the initiatorPrincipalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestTopup.Context.InitiatorPrincipalId }
         *     
         */
        public void setInitiatorPrincipalId(RequestTopup.Context.InitiatorPrincipalId value) {
            this.initiatorPrincipalId = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "type",
            "userId"
        })
        public static class InitiatorPrincipalId {

            @XmlElement(required = true)
            protected String id;
            @XmlElement(required = true)
            protected String type;
            @XmlElement(required = true)
            protected String userId;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the userId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserId() {
                return userId;
            }

            /**
             * Sets the value of the userId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserId(String value) {
                this.userId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="accountTypeId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountId",
        "accountTypeId"
    })
    public static class SenderAccountSpecifier {

        @XmlElement(required = true)
        protected String accountId;
        @XmlElement(required = true)
        protected String accountTypeId;

        /**
         * Gets the value of the accountId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountId() {
            return accountId;
        }

        /**
         * Sets the value of the accountId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountId(String value) {
            this.accountId = value;
        }

        /**
         * Gets the value of the accountTypeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountTypeId() {
            return accountTypeId;
        }

        /**
         * Sets the value of the accountTypeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountTypeId(String value) {
            this.accountTypeId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "type",
        "userId"
    })
    public static class SenderPrincipalId {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String userId;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the userId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserId(String value) {
            this.userId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="accountTypeId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountId",
        "accountTypeId"
    })
    public static class TopupAccountSpecifier {

        @XmlElement(required = true)
        protected String accountId;
        @XmlElement(required = true)
        protected String accountTypeId;

        /**
         * Gets the value of the accountId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountId() {
            return accountId;
        }

        /**
         * Sets the value of the accountId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountId(String value) {
            this.accountId = value;
        }

        /**
         * Gets the value of the accountTypeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountTypeId() {
            return accountTypeId;
        }

        /**
         * Sets the value of the accountTypeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountTypeId(String value) {
            this.accountTypeId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "type",
        "userId"
    })
    public static class TopupPrincipalId {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String userId;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the userId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserId(String value) {
            this.userId = value;
        }

    }

}
