//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.20 at 03:00:10 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.guide/soap/server", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.factorialsystems.msscprovider.wsdl.airtel;
