//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.20 at 01:51:45 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.mtn;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.factorialsystems.msscprovider.wsdl.mtn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.factorialsystems.msscprovider.wsdl.mtn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VendResponse }
     * 
     */
    public VendResponse createVendResponse() {
        return new VendResponse();
    }

    /**
     * Create an instance of {@link Vend }
     * 
     */
    public Vend createVend() {
        return new Vend();
    }

}
