//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.19 at 01:39:42 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.ekedp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.factorialsystems.msscprovider.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BaseResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "baseResponse");
    private final static QName _ChargeWalletV2_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "chargeWalletV2");
    private final static QName _ChargeWalletV2Response_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "chargeWalletV2Response");
    private final static QName _CustomerInfo_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "customerInfo");
    private final static QName _CustomerInfoResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "customerInfoResponse");
    private final static QName _GetBalance_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "getBalance");
    private final static QName _GetBalanceResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "getBalanceResponse");
    private final static QName _GetOrderDetailsV2_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "getOrderDetailsV2");
    private final static QName _GetOrderDetailsV2Response_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "getOrderDetailsV2Response");
    private final static QName _GetTransactionHistoryV2_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "getTransactionHistoryV2");
    private final static QName _GetTransactionHistoryV2Response_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "getTransactionHistoryV2Response");
    private final static QName _Login_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "login");
    private final static QName _LoginResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "loginResponse");
    private final static QName _Logout_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "logout");
    private final static QName _LogoutResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "logoutResponse");
    private final static QName _NotifyForReversal_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "notifyForReversal");
    private final static QName _NotifyForReversalResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "notifyForReversalResponse");
    private final static QName _NotifyReversalResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "notifyReversalResponse");
    private final static QName _OrderDetails_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "orderDetails");
    private final static QName _SessionResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "sessionResponse");
    private final static QName _StagedCashin_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "stagedCashin");
    private final static QName _StartSession_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "startSession");
    private final static QName _StartSessionResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "startSessionResponse");
    private final static QName _TransactionParams_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "transactionParams");
    private final static QName _ValidateCustomer_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "validateCustomer");
    private final static QName _ValidateCustomerResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "validateCustomerResponse");
    private final static QName _ValidatePayment_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "validatePayment");
    private final static QName _ValidatePaymentResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "validatePaymentResponse");
    private final static QName _ValidatePaymentResponseV2_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "validatePaymentResponseV2");
    private final static QName _ValidationInfo_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "validationInfo");
    private final static QName _WalletResponse_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "walletResponse");
    private final static QName _SessionId_QNAME = new QName("http://soap.convergenceondemand.net/TMP/", "sessionId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.factorialsystems.msscprovider.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidationParams }
     * 
     */
    public ValidationParams createValidationParams() {
        return new ValidationParams();
    }

    /**
     * Create an instance of {@link ValidationParams.ExtraData }
     * 
     */
    public ValidationParams.ExtraData createValidationParamsExtraData() {
        return new ValidationParams.ExtraData();
    }

    /**
     * Create an instance of {@link ValidationInfo }
     * 
     */
    public ValidationInfo createValidationInfo() {
        return new ValidationInfo();
    }

    /**
     * Create an instance of {@link ValidationInfo.ExtraData }
     * 
     */
    public ValidationInfo.ExtraData createValidationInfoExtraData() {
        return new ValidationInfo.ExtraData();
    }

    /**
     * Create an instance of {@link TransactionParams }
     * 
     */
    public TransactionParams createTransactionParams() {
        return new TransactionParams();
    }

    /**
     * Create an instance of {@link TransactionParams.ExtraData }
     * 
     */
    public TransactionParams.ExtraData createTransactionParamsExtraData() {
        return new TransactionParams.ExtraData();
    }

    /**
     * Create an instance of {@link OrderDetails }
     * 
     */
    public OrderDetails createOrderDetails() {
        return new OrderDetails();
    }

    /**
     * Create an instance of {@link OrderDetails.ExtraData }
     * 
     */
    public OrderDetails.ExtraData createOrderDetailsExtraData() {
        return new OrderDetails.ExtraData();
    }

    /**
     * Create an instance of {@link BaseResponse }
     * 
     */
    public BaseResponse createBaseResponse() {
        return new BaseResponse();
    }

    /**
     * Create an instance of {@link ChargeWalletV2 }
     * 
     */
    public ChargeWalletV2 createChargeWalletV2() {
        return new ChargeWalletV2();
    }

    /**
     * Create an instance of {@link ChargeWalletV2Response }
     * 
     */
    public ChargeWalletV2Response createChargeWalletV2Response() {
        return new ChargeWalletV2Response();
    }

    /**
     * Create an instance of {@link CustomerInfo }
     * 
     */
    public CustomerInfo createCustomerInfo() {
        return new CustomerInfo();
    }

    /**
     * Create an instance of {@link CustomerInfoResponse }
     * 
     */
    public CustomerInfoResponse createCustomerInfoResponse() {
        return new CustomerInfoResponse();
    }

    /**
     * Create an instance of {@link GetBalance }
     * 
     */
    public GetBalance createGetBalance() {
        return new GetBalance();
    }

    /**
     * Create an instance of {@link GetBalanceResponse }
     * 
     */
    public GetBalanceResponse createGetBalanceResponse() {
        return new GetBalanceResponse();
    }

    /**
     * Create an instance of {@link GetOrderDetailsV2 }
     * 
     */
    public GetOrderDetailsV2 createGetOrderDetailsV2() {
        return new GetOrderDetailsV2();
    }

    /**
     * Create an instance of {@link GetOrderDetailsV2Response }
     * 
     */
    public GetOrderDetailsV2Response createGetOrderDetailsV2Response() {
        return new GetOrderDetailsV2Response();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryV2 }
     * 
     */
    public GetTransactionHistoryV2 createGetTransactionHistoryV2() {
        return new GetTransactionHistoryV2();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryV2Response }
     * 
     */
    public GetTransactionHistoryV2Response createGetTransactionHistoryV2Response() {
        return new GetTransactionHistoryV2Response();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link NotifyForReversal }
     * 
     */
    public NotifyForReversal createNotifyForReversal() {
        return new NotifyForReversal();
    }

    /**
     * Create an instance of {@link NotifyForReversalResponse }
     * 
     */
    public NotifyForReversalResponse createNotifyForReversalResponse() {
        return new NotifyForReversalResponse();
    }

    /**
     * Create an instance of {@link NotifyReversalResponse }
     * 
     */
    public NotifyReversalResponse createNotifyReversalResponse() {
        return new NotifyReversalResponse();
    }

    /**
     * Create an instance of {@link SessionResponse }
     * 
     */
    public SessionResponse createSessionResponse() {
        return new SessionResponse();
    }

    /**
     * Create an instance of {@link StagedCashin }
     * 
     */
    public StagedCashin createStagedCashin() {
        return new StagedCashin();
    }

    /**
     * Create an instance of {@link StartSession }
     * 
     */
    public StartSession createStartSession() {
        return new StartSession();
    }

    /**
     * Create an instance of {@link StartSessionResponse }
     * 
     */
    public StartSessionResponse createStartSessionResponse() {
        return new StartSessionResponse();
    }

    /**
     * Create an instance of {@link ValidateCustomer }
     * 
     */
    public ValidateCustomer createValidateCustomer() {
        return new ValidateCustomer();
    }

    /**
     * Create an instance of {@link ValidateCustomerResponse }
     * 
     */
    public ValidateCustomerResponse createValidateCustomerResponse() {
        return new ValidateCustomerResponse();
    }

    /**
     * Create an instance of {@link ValidatePayment }
     * 
     */
    public ValidatePayment createValidatePayment() {
        return new ValidatePayment();
    }

    /**
     * Create an instance of {@link ValidatePaymentResponse }
     * 
     */
    public ValidatePaymentResponse createValidatePaymentResponse() {
        return new ValidatePaymentResponse();
    }

    /**
     * Create an instance of {@link ValidatePaymentResponseV2 }
     * 
     */
    public ValidatePaymentResponseV2 createValidatePaymentResponseV2() {
        return new ValidatePaymentResponseV2();
    }

    /**
     * Create an instance of {@link WalletResponse }
     * 
     */
    public WalletResponse createWalletResponse() {
        return new WalletResponse();
    }

    /**
     * Create an instance of {@link OrderDetailsResponse }
     * 
     */
    public OrderDetailsResponse createOrderDetailsResponse() {
        return new OrderDetailsResponse();
    }

    /**
     * Create an instance of {@link TokenData }
     * 
     */
    public TokenData createTokenData() {
        return new TokenData();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link Debt }
     * 
     */
    public Debt createDebt() {
        return new Debt();
    }

    /**
     * Create an instance of {@link Fixed }
     * 
     */
    public Fixed createFixed() {
        return new Fixed();
    }

    /**
     * Create an instance of {@link VendStatus }
     * 
     */
    public VendStatus createVendStatus() {
        return new VendStatus();
    }

    /**
     * Create an instance of {@link Util }
     * 
     */
    public Util createUtil() {
        return new Util();
    }

    /**
     * Create an instance of {@link BillingHistoryResponse }
     * 
     */
    public BillingHistoryResponse createBillingHistoryResponse() {
        return new BillingHistoryResponse();
    }

    /**
     * Create an instance of {@link ValidationParams.ExtraData.Entry }
     * 
     */
    public ValidationParams.ExtraData.Entry createValidationParamsExtraDataEntry() {
        return new ValidationParams.ExtraData.Entry();
    }

    /**
     * Create an instance of {@link ValidationInfo.ExtraData.Entry }
     * 
     */
    public ValidationInfo.ExtraData.Entry createValidationInfoExtraDataEntry() {
        return new ValidationInfo.ExtraData.Entry();
    }

    /**
     * Create an instance of {@link TransactionParams.ExtraData.Entry }
     * 
     */
    public TransactionParams.ExtraData.Entry createTransactionParamsExtraDataEntry() {
        return new TransactionParams.ExtraData.Entry();
    }

    /**
     * Create an instance of {@link OrderDetails.ExtraData.Entry }
     * 
     */
    public OrderDetails.ExtraData.Entry createOrderDetailsExtraDataEntry() {
        return new OrderDetails.ExtraData.Entry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BaseResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "baseResponse")
    public JAXBElement<BaseResponse> createBaseResponse(BaseResponse value) {
        return new JAXBElement<BaseResponse>(_BaseResponse_QNAME, BaseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeWalletV2 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChargeWalletV2 }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "chargeWalletV2")
    public JAXBElement<ChargeWalletV2> createChargeWalletV2(ChargeWalletV2 value) {
        return new JAXBElement<ChargeWalletV2>(_ChargeWalletV2_QNAME, ChargeWalletV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeWalletV2Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChargeWalletV2Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "chargeWalletV2Response")
    public JAXBElement<ChargeWalletV2Response> createChargeWalletV2Response(ChargeWalletV2Response value) {
        return new JAXBElement<ChargeWalletV2Response>(_ChargeWalletV2Response_QNAME, ChargeWalletV2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "customerInfo")
    public JAXBElement<CustomerInfo> createCustomerInfo(CustomerInfo value) {
        return new JAXBElement<CustomerInfo>(_CustomerInfo_QNAME, CustomerInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "customerInfoResponse")
    public JAXBElement<CustomerInfoResponse> createCustomerInfoResponse(CustomerInfoResponse value) {
        return new JAXBElement<CustomerInfoResponse>(_CustomerInfoResponse_QNAME, CustomerInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBalance }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBalance }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "getBalance")
    public JAXBElement<GetBalance> createGetBalance(GetBalance value) {
        return new JAXBElement<GetBalance>(_GetBalance_QNAME, GetBalance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBalanceResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBalanceResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "getBalanceResponse")
    public JAXBElement<GetBalanceResponse> createGetBalanceResponse(GetBalanceResponse value) {
        return new JAXBElement<GetBalanceResponse>(_GetBalanceResponse_QNAME, GetBalanceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderDetailsV2 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetOrderDetailsV2 }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "getOrderDetailsV2")
    public JAXBElement<GetOrderDetailsV2> createGetOrderDetailsV2(GetOrderDetailsV2 value) {
        return new JAXBElement<GetOrderDetailsV2>(_GetOrderDetailsV2_QNAME, GetOrderDetailsV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderDetailsV2Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetOrderDetailsV2Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "getOrderDetailsV2Response")
    public JAXBElement<GetOrderDetailsV2Response> createGetOrderDetailsV2Response(GetOrderDetailsV2Response value) {
        return new JAXBElement<GetOrderDetailsV2Response>(_GetOrderDetailsV2Response_QNAME, GetOrderDetailsV2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryV2 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryV2 }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "getTransactionHistoryV2")
    public JAXBElement<GetTransactionHistoryV2> createGetTransactionHistoryV2(GetTransactionHistoryV2 value) {
        return new JAXBElement<GetTransactionHistoryV2>(_GetTransactionHistoryV2_QNAME, GetTransactionHistoryV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryV2Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryV2Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "getTransactionHistoryV2Response")
    public JAXBElement<GetTransactionHistoryV2Response> createGetTransactionHistoryV2Response(GetTransactionHistoryV2Response value) {
        return new JAXBElement<GetTransactionHistoryV2Response>(_GetTransactionHistoryV2Response_QNAME, GetTransactionHistoryV2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Login }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Login }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "login")
    public JAXBElement<Login> createLogin(Login value) {
        return new JAXBElement<Login>(_Login_QNAME, Login.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "loginResponse")
    public JAXBElement<LoginResponse> createLoginResponse(LoginResponse value) {
        return new JAXBElement<LoginResponse>(_LoginResponse_QNAME, LoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Logout }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Logout }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "logout")
    public JAXBElement<Logout> createLogout(Logout value) {
        return new JAXBElement<Logout>(_Logout_QNAME, Logout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoutResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogoutResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "logoutResponse")
    public JAXBElement<LogoutResponse> createLogoutResponse(LogoutResponse value) {
        return new JAXBElement<LogoutResponse>(_LogoutResponse_QNAME, LogoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyForReversal }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotifyForReversal }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "notifyForReversal")
    public JAXBElement<NotifyForReversal> createNotifyForReversal(NotifyForReversal value) {
        return new JAXBElement<NotifyForReversal>(_NotifyForReversal_QNAME, NotifyForReversal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyForReversalResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotifyForReversalResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "notifyForReversalResponse")
    public JAXBElement<NotifyForReversalResponse> createNotifyForReversalResponse(NotifyForReversalResponse value) {
        return new JAXBElement<NotifyForReversalResponse>(_NotifyForReversalResponse_QNAME, NotifyForReversalResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyReversalResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotifyReversalResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "notifyReversalResponse")
    public JAXBElement<NotifyReversalResponse> createNotifyReversalResponse(NotifyReversalResponse value) {
        return new JAXBElement<NotifyReversalResponse>(_NotifyReversalResponse_QNAME, NotifyReversalResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OrderDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "orderDetails")
    public JAXBElement<OrderDetails> createOrderDetails(OrderDetails value) {
        return new JAXBElement<OrderDetails>(_OrderDetails_QNAME, OrderDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessionResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SessionResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "sessionResponse")
    public JAXBElement<SessionResponse> createSessionResponse(SessionResponse value) {
        return new JAXBElement<SessionResponse>(_SessionResponse_QNAME, SessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StagedCashin }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StagedCashin }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "stagedCashin")
    public JAXBElement<StagedCashin> createStagedCashin(StagedCashin value) {
        return new JAXBElement<StagedCashin>(_StagedCashin_QNAME, StagedCashin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartSession }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StartSession }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "startSession")
    public JAXBElement<StartSession> createStartSession(StartSession value) {
        return new JAXBElement<StartSession>(_StartSession_QNAME, StartSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartSessionResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StartSessionResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "startSessionResponse")
    public JAXBElement<StartSessionResponse> createStartSessionResponse(StartSessionResponse value) {
        return new JAXBElement<StartSessionResponse>(_StartSessionResponse_QNAME, StartSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionParams }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionParams }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "transactionParams")
    public JAXBElement<TransactionParams> createTransactionParams(TransactionParams value) {
        return new JAXBElement<TransactionParams>(_TransactionParams_QNAME, TransactionParams.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "validateCustomer")
    public JAXBElement<ValidateCustomer> createValidateCustomer(ValidateCustomer value) {
        return new JAXBElement<ValidateCustomer>(_ValidateCustomer_QNAME, ValidateCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "validateCustomerResponse")
    public JAXBElement<ValidateCustomerResponse> createValidateCustomerResponse(ValidateCustomerResponse value) {
        return new JAXBElement<ValidateCustomerResponse>(_ValidateCustomerResponse_QNAME, ValidateCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidatePayment }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidatePayment }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "validatePayment")
    public JAXBElement<ValidatePayment> createValidatePayment(ValidatePayment value) {
        return new JAXBElement<ValidatePayment>(_ValidatePayment_QNAME, ValidatePayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidatePaymentResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidatePaymentResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "validatePaymentResponse")
    public JAXBElement<ValidatePaymentResponse> createValidatePaymentResponse(ValidatePaymentResponse value) {
        return new JAXBElement<ValidatePaymentResponse>(_ValidatePaymentResponse_QNAME, ValidatePaymentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidatePaymentResponseV2 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidatePaymentResponseV2 }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "validatePaymentResponseV2")
    public JAXBElement<ValidatePaymentResponseV2> createValidatePaymentResponseV2(ValidatePaymentResponseV2 value) {
        return new JAXBElement<ValidatePaymentResponseV2>(_ValidatePaymentResponseV2_QNAME, ValidatePaymentResponseV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidationInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "validationInfo")
    public JAXBElement<ValidationInfo> createValidationInfo(ValidationInfo value) {
        return new JAXBElement<ValidationInfo>(_ValidationInfo_QNAME, ValidationInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WalletResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WalletResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "walletResponse")
    public JAXBElement<WalletResponse> createWalletResponse(WalletResponse value) {
        return new JAXBElement<WalletResponse>(_WalletResponse_QNAME, WalletResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.convergenceondemand.net/TMP/", name = "sessionId")
    public JAXBElement<String> createSessionId(String value) {
        return new JAXBElement<String>(_SessionId_QNAME, String.class, null, value);
    }

}
