//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.19 at 01:39:42 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.ekedp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tokenData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tokenData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="algCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bsstToken" type="{http://soap.convergenceondemand.net/TMP/}token" minOccurs="0"/&gt;
 *         &lt;element name="customerMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="daysLastVend" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="debt" type="{http://soap.convergenceondemand.net/TMP/}debt" minOccurs="0"/&gt;
 *         &lt;element name="extraRemDebt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fixed" type="{http://soap.convergenceondemand.net/TMP/}fixed" minOccurs="0"/&gt;
 *         &lt;element name="invMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isTrial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="keyChangeToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="keyRevNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mrktMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="resource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rtlrMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://soap.convergenceondemand.net/TMP/}vendStatus" minOccurs="0"/&gt;
 *         &lt;element name="stdToken" type="{http://soap.convergenceondemand.net/TMP/}token" minOccurs="0"/&gt;
 *         &lt;element name="supGrpRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tariff" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tariffIdx" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tokenTechCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="totalOpenDebt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="totalRemDebt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="util" type="{http://soap.convergenceondemand.net/TMP/}util" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tokenData", propOrder = {
    "algCode",
    "bsstToken",
    "customerMsg",
    "daysLastVend",
    "debt",
    "extraRemDebt",
    "fixed",
    "invMsg",
    "isTrial",
    "keyChangeToken",
    "keyRevNum",
    "mrktMsg",
    "resource",
    "rtlrMsg",
    "status",
    "stdToken",
    "supGrpRef",
    "tariff",
    "tariffIdx",
    "tokenTechCode",
    "totalOpenDebt",
    "totalRemDebt",
    "util"
})
public class TokenData {

    protected String algCode;
    protected Token bsstToken;
    protected String customerMsg;
    protected String daysLastVend;
    protected Debt debt;
    protected String extraRemDebt;
    protected Fixed fixed;
    protected String invMsg;
    protected String isTrial;
    protected String keyChangeToken;
    protected String keyRevNum;
    protected String mrktMsg;
    protected String resource;
    protected String rtlrMsg;
    protected VendStatus status;
    protected Token stdToken;
    protected String supGrpRef;
    protected String tariff;
    protected String tariffIdx;
    protected String tokenTechCode;
    protected String totalOpenDebt;
    protected String totalRemDebt;
    protected Util util;

    /**
     * Gets the value of the algCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlgCode() {
        return algCode;
    }

    /**
     * Sets the value of the algCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgCode(String value) {
        this.algCode = value;
    }

    /**
     * Gets the value of the bsstToken property.
     * 
     * @return
     *     possible object is
     *     {@link Token }
     *     
     */
    public Token getBsstToken() {
        return bsstToken;
    }

    /**
     * Sets the value of the bsstToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link Token }
     *     
     */
    public void setBsstToken(Token value) {
        this.bsstToken = value;
    }

    /**
     * Gets the value of the customerMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMsg() {
        return customerMsg;
    }

    /**
     * Sets the value of the customerMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMsg(String value) {
        this.customerMsg = value;
    }

    /**
     * Gets the value of the daysLastVend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysLastVend() {
        return daysLastVend;
    }

    /**
     * Sets the value of the daysLastVend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysLastVend(String value) {
        this.daysLastVend = value;
    }

    /**
     * Gets the value of the debt property.
     * 
     * @return
     *     possible object is
     *     {@link Debt }
     *     
     */
    public Debt getDebt() {
        return debt;
    }

    /**
     * Sets the value of the debt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Debt }
     *     
     */
    public void setDebt(Debt value) {
        this.debt = value;
    }

    /**
     * Gets the value of the extraRemDebt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraRemDebt() {
        return extraRemDebt;
    }

    /**
     * Sets the value of the extraRemDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraRemDebt(String value) {
        this.extraRemDebt = value;
    }

    /**
     * Gets the value of the fixed property.
     * 
     * @return
     *     possible object is
     *     {@link Fixed }
     *     
     */
    public Fixed getFixed() {
        return fixed;
    }

    /**
     * Sets the value of the fixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fixed }
     *     
     */
    public void setFixed(Fixed value) {
        this.fixed = value;
    }

    /**
     * Gets the value of the invMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvMsg() {
        return invMsg;
    }

    /**
     * Sets the value of the invMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvMsg(String value) {
        this.invMsg = value;
    }

    /**
     * Gets the value of the isTrial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTrial() {
        return isTrial;
    }

    /**
     * Sets the value of the isTrial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTrial(String value) {
        this.isTrial = value;
    }

    /**
     * Gets the value of the keyChangeToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyChangeToken() {
        return keyChangeToken;
    }

    /**
     * Sets the value of the keyChangeToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyChangeToken(String value) {
        this.keyChangeToken = value;
    }

    /**
     * Gets the value of the keyRevNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyRevNum() {
        return keyRevNum;
    }

    /**
     * Sets the value of the keyRevNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyRevNum(String value) {
        this.keyRevNum = value;
    }

    /**
     * Gets the value of the mrktMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrktMsg() {
        return mrktMsg;
    }

    /**
     * Sets the value of the mrktMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrktMsg(String value) {
        this.mrktMsg = value;
    }

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResource(String value) {
        this.resource = value;
    }

    /**
     * Gets the value of the rtlrMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtlrMsg() {
        return rtlrMsg;
    }

    /**
     * Sets the value of the rtlrMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtlrMsg(String value) {
        this.rtlrMsg = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link VendStatus }
     *     
     */
    public VendStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendStatus }
     *     
     */
    public void setStatus(VendStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the stdToken property.
     * 
     * @return
     *     possible object is
     *     {@link Token }
     *     
     */
    public Token getStdToken() {
        return stdToken;
    }

    /**
     * Sets the value of the stdToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link Token }
     *     
     */
    public void setStdToken(Token value) {
        this.stdToken = value;
    }

    /**
     * Gets the value of the supGrpRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupGrpRef() {
        return supGrpRef;
    }

    /**
     * Sets the value of the supGrpRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupGrpRef(String value) {
        this.supGrpRef = value;
    }

    /**
     * Gets the value of the tariff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariff() {
        return tariff;
    }

    /**
     * Sets the value of the tariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariff(String value) {
        this.tariff = value;
    }

    /**
     * Gets the value of the tariffIdx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffIdx() {
        return tariffIdx;
    }

    /**
     * Sets the value of the tariffIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffIdx(String value) {
        this.tariffIdx = value;
    }

    /**
     * Gets the value of the tokenTechCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenTechCode() {
        return tokenTechCode;
    }

    /**
     * Sets the value of the tokenTechCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenTechCode(String value) {
        this.tokenTechCode = value;
    }

    /**
     * Gets the value of the totalOpenDebt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalOpenDebt() {
        return totalOpenDebt;
    }

    /**
     * Sets the value of the totalOpenDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalOpenDebt(String value) {
        this.totalOpenDebt = value;
    }

    /**
     * Gets the value of the totalRemDebt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalRemDebt() {
        return totalRemDebt;
    }

    /**
     * Sets the value of the totalRemDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalRemDebt(String value) {
        this.totalRemDebt = value;
    }

    /**
     * Gets the value of the util property.
     * 
     * @return
     *     possible object is
     *     {@link Util }
     *     
     */
    public Util getUtil() {
        return util;
    }

    /**
     * Sets the value of the util property.
     * 
     * @param value
     *     allowed object is
     *     {@link Util }
     *     
     */
    public void setUtil(Util value) {
        this.util = value;
    }

}
