version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: providerdb
    volumes:
      - ./data:/docker-entrypoint-initdb.d

    networks:
      - onecard-network

networks:
  onecard-network:
    name: onecard
    driver: bridge