//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BalanceTransfer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BalanceTransfer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xml.smilecoms.com/schema/TPGW}TPGWObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FromAccountId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="ToAccountId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ToPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="CustomerEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransferAmountInCents" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ChannelUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UniqueTransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BalanceTransfer", propOrder = {
    "fromAccountId",
    "toAccountId",
    "toPhoneNumber",
    "customerEmailAddress",
    "transferAmountInCents",
    "channelUsed",
    "hash",
    "currency",
    "uniqueTransactionId"
})
public class BalanceTransfer
    extends TPGWObject
{

    @XmlElement(name = "FromAccountId")
    protected long fromAccountId;
    @XmlElement(name = "ToAccountId", defaultValue = "0")
    protected Long toAccountId;
    @XmlElement(name = "ToPhoneNumber", defaultValue = "0")
    protected Long toPhoneNumber;
    @XmlElement(name = "CustomerEmailAddress")
    protected String customerEmailAddress;
    @XmlElement(name = "TransferAmountInCents")
    protected double transferAmountInCents;
    @XmlElement(name = "ChannelUsed")
    protected String channelUsed;
    @XmlElement(name = "Hash")
    protected String hash;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "UniqueTransactionId", required = true)
    protected String uniqueTransactionId;

    /**
     * Gets the value of the fromAccountId property.
     * 
     */
    public long getFromAccountId() {
        return fromAccountId;
    }

    /**
     * Sets the value of the fromAccountId property.
     * 
     */
    public void setFromAccountId(long value) {
        this.fromAccountId = value;
    }

    /**
     * Gets the value of the toAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getToAccountId() {
        return toAccountId;
    }

    /**
     * Sets the value of the toAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setToAccountId(Long value) {
        this.toAccountId = value;
    }

    /**
     * Gets the value of the toPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getToPhoneNumber() {
        return toPhoneNumber;
    }

    /**
     * Sets the value of the toPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setToPhoneNumber(Long value) {
        this.toPhoneNumber = value;
    }

    /**
     * Gets the value of the customerEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmailAddress() {
        return customerEmailAddress;
    }

    /**
     * Sets the value of the customerEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmailAddress(String value) {
        this.customerEmailAddress = value;
    }

    /**
     * Gets the value of the transferAmountInCents property.
     * 
     */
    public double getTransferAmountInCents() {
        return transferAmountInCents;
    }

    /**
     * Sets the value of the transferAmountInCents property.
     * 
     */
    public void setTransferAmountInCents(double value) {
        this.transferAmountInCents = value;
    }

    /**
     * Gets the value of the channelUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelUsed() {
        return channelUsed;
    }

    /**
     * Sets the value of the channelUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelUsed(String value) {
        this.channelUsed = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the uniqueTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueTransactionId() {
        return uniqueTransactionId;
    }

    /**
     * Sets the value of the uniqueTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueTransactionId(String value) {
        this.uniqueTransactionId = value;
    }

}
