//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bundle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bundle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xml.smilecoms.com/schema/TPGW}TPGWObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BundleTypeCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="BundleDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BundlePrice" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ValidityDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bundle", propOrder = {
    "bundleTypeCode",
    "bundleDescription",
    "bundlePrice",
    "validityDays"
})
public class Bundle
    extends TPGWObject
{

    @XmlElement(name = "BundleTypeCode")
    protected int bundleTypeCode;
    @XmlElement(name = "BundleDescription", required = true)
    protected String bundleDescription;
    @XmlElement(name = "BundlePrice")
    protected double bundlePrice;
    @XmlElement(name = "ValidityDays")
    protected Integer validityDays;

    /**
     * Gets the value of the bundleTypeCode property.
     * 
     */
    public int getBundleTypeCode() {
        return bundleTypeCode;
    }

    /**
     * Sets the value of the bundleTypeCode property.
     * 
     */
    public void setBundleTypeCode(int value) {
        this.bundleTypeCode = value;
    }

    /**
     * Gets the value of the bundleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundleDescription() {
        return bundleDescription;
    }

    /**
     * Sets the value of the bundleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundleDescription(String value) {
        this.bundleDescription = value;
    }

    /**
     * Gets the value of the bundlePrice property.
     * 
     */
    public double getBundlePrice() {
        return bundlePrice;
    }

    /**
     * Sets the value of the bundlePrice property.
     * 
     */
    public void setBundlePrice(double value) {
        this.bundlePrice = value;
    }

    /**
     * Gets the value of the validityDays property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValidityDays() {
        return validityDays;
    }

    /**
     * Sets the value of the validityDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValidityDays(Integer value) {
        this.validityDays = value;
    }

}
