//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuyBundle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuyBundle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xml.smilecoms.com/schema/TPGW}TPGWObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BundleTypeCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CustomerAccountId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="CustomerEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="QuantityBought" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CustomerTenderedAmountInCents" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="UniqueTransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ChannelUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuyBundle", propOrder = {
    "bundleTypeCode",
    "customerAccountId",
    "phoneNumber",
    "customerEmailAddress",
    "quantityBought",
    "customerTenderedAmountInCents",
    "uniqueTransactionId",
    "channelUsed",
    "hash",
    "currency"
})
public class BuyBundle
    extends TPGWObject
{

    @XmlElement(name = "BundleTypeCode")
    protected int bundleTypeCode;
    @XmlElement(name = "CustomerAccountId", defaultValue = "0")
    protected Long customerAccountId;
    @XmlElement(name = "PhoneNumber", defaultValue = "0")
    protected Long phoneNumber;
    @XmlElement(name = "CustomerEmailAddress")
    protected String customerEmailAddress;
    @XmlElement(name = "QuantityBought")
    protected int quantityBought;
    @XmlElement(name = "CustomerTenderedAmountInCents")
    protected double customerTenderedAmountInCents;
    @XmlElement(name = "UniqueTransactionId", required = true)
    protected String uniqueTransactionId;
    @XmlElement(name = "ChannelUsed")
    protected String channelUsed;
    @XmlElement(name = "Hash")
    protected String hash;
    @XmlElement(name = "Currency")
    protected String currency;

    /**
     * Gets the value of the bundleTypeCode property.
     * 
     */
    public int getBundleTypeCode() {
        return bundleTypeCode;
    }

    /**
     * Sets the value of the bundleTypeCode property.
     * 
     */
    public void setBundleTypeCode(int value) {
        this.bundleTypeCode = value;
    }

    /**
     * Gets the value of the customerAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCustomerAccountId() {
        return customerAccountId;
    }

    /**
     * Sets the value of the customerAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCustomerAccountId(Long value) {
        this.customerAccountId = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPhoneNumber(Long value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the customerEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmailAddress() {
        return customerEmailAddress;
    }

    /**
     * Sets the value of the customerEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmailAddress(String value) {
        this.customerEmailAddress = value;
    }

    /**
     * Gets the value of the quantityBought property.
     * 
     */
    public int getQuantityBought() {
        return quantityBought;
    }

    /**
     * Sets the value of the quantityBought property.
     * 
     */
    public void setQuantityBought(int value) {
        this.quantityBought = value;
    }

    /**
     * Gets the value of the customerTenderedAmountInCents property.
     * 
     */
    public double getCustomerTenderedAmountInCents() {
        return customerTenderedAmountInCents;
    }

    /**
     * Sets the value of the customerTenderedAmountInCents property.
     * 
     */
    public void setCustomerTenderedAmountInCents(double value) {
        this.customerTenderedAmountInCents = value;
    }

    /**
     * Gets the value of the uniqueTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueTransactionId() {
        return uniqueTransactionId;
    }

    /**
     * Sets the value of the uniqueTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueTransactionId(String value) {
        this.uniqueTransactionId = value;
    }

    /**
     * Gets the value of the channelUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelUsed() {
        return channelUsed;
    }

    /**
     * Sets the value of the channelUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelUsed(String value) {
        this.channelUsed = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

}
