//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.factorialsystems.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
    private final static QName _TPGWError_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "TPGWError");
    private final static QName _IsUpRequest_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "IsUpRequest");
    private final static QName _Done_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "Done");
    private final static QName _Authenticate_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "Authenticate");
    private final static QName _AuthenticateResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "AuthenticateResult");
    private final static QName _TransactionStatusQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "TransactionStatusQuery");
    private final static QName _TransactionStatusResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "TransactionStatusResult");
    private final static QName _BalanceQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BalanceQuery");
    private final static QName _BalanceResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BalanceResult");
    private final static QName _DataBalanceQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "DataBalanceQuery");
    private final static QName _DataBalanceResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "DataBalanceResult");
    private final static QName _BalanceTransfer_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BalanceTransfer");
    private final static QName _BalanceTransferResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BalanceTransferResult");
    private final static QName _ValidateAccountQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidateAccountQuery");
    private final static QName _CustomerIdByAccountIdQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "CustomerIdByAccountIdQuery");
    private final static QName _NinByAccountIdOrPhoneNumberQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "NinByAccountIdOrPhoneNumberQuery");
    private final static QName _ValidatePhoneNumberQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidatePhoneNumberQuery");
    private final static QName _ValidateEmailAddressQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidateEmailAddressQuery");
    private final static QName _VoucherDetailQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "VoucherDetailQuery");
    private final static QName _VoucherDetailResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "VoucherDetailResult");
    private final static QName _RedemPrepaidStrip_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "RedemPrepaidStrip");
    private final static QName _RedemPrepaidStripResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "RedemPrepaidStripResult");
    private final static QName _ValidateAccountResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidateAccountResult");
    private final static QName _CustomerIdByAccountIdResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "CustomerIdByAccountIdResult");
    private final static QName _NinByAccountIdOrPhoneNumberResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "NinByAccountIdOrPhoneNumberResult");
    private final static QName _ValidatePhoneNumberResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidatePhoneNumberResult");
    private final static QName _ValidateEmailAddressResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidateEmailAddressResult");
    private final static QName _BundleCatalogueQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BundleCatalogueQuery");
    private final static QName _BundleCatalogueResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BundleCatalogueResult");
    private final static QName _BuyBundle_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BuyBundle");
    private final static QName _BuyBundleResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BuyBundleResult");
    private final static QName _BuyBundleUsingPriceInCentsData_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BuyBundleUsingPriceInCentsData");
    private final static QName _BuyBundleUsingPriceInCentsResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "BuyBundleUsingPriceInCentsResult");
    private final static QName _NewCustomer_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "NewCustomer");
    private final static QName _Customer_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "Customer");
    private final static QName _AddCustomerResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "AddCustomerResult");
    private final static QName _ValidateReferenceIdQuery_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidateReferenceIdQuery");
    private final static QName _ValidateReferenceIdResult_QNAME = new QName("http://xml.smilecoms.com/schema/TPGW", "ValidateReferenceIdResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.factorialsystems.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TPGWError }
     * 
     */
    public TPGWError createTPGWError() {
        return new TPGWError();
    }

    /**
     * Create an instance of {@link Done }
     * 
     */
    public Done createDone() {
        return new Done();
    }

    /**
     * Create an instance of {@link Authenticate }
     * 
     */
    public Authenticate createAuthenticate() {
        return new Authenticate();
    }

    /**
     * Create an instance of {@link AuthenticateResult }
     * 
     */
    public AuthenticateResult createAuthenticateResult() {
        return new AuthenticateResult();
    }

    /**
     * Create an instance of {@link TransactionStatusQuery }
     * 
     */
    public TransactionStatusQuery createTransactionStatusQuery() {
        return new TransactionStatusQuery();
    }

    /**
     * Create an instance of {@link TransactionStatusResult }
     * 
     */
    public TransactionStatusResult createTransactionStatusResult() {
        return new TransactionStatusResult();
    }

    /**
     * Create an instance of {@link BalanceQuery }
     * 
     */
    public BalanceQuery createBalanceQuery() {
        return new BalanceQuery();
    }

    /**
     * Create an instance of {@link BalanceResult }
     * 
     */
    public BalanceResult createBalanceResult() {
        return new BalanceResult();
    }

    /**
     * Create an instance of {@link DataBalanceQuery }
     * 
     */
    public DataBalanceQuery createDataBalanceQuery() {
        return new DataBalanceQuery();
    }

    /**
     * Create an instance of {@link DataBalanceResult }
     * 
     */
    public DataBalanceResult createDataBalanceResult() {
        return new DataBalanceResult();
    }

    /**
     * Create an instance of {@link BalanceTransfer }
     * 
     */
    public BalanceTransfer createBalanceTransfer() {
        return new BalanceTransfer();
    }

    /**
     * Create an instance of {@link BalanceTransferResult }
     * 
     */
    public BalanceTransferResult createBalanceTransferResult() {
        return new BalanceTransferResult();
    }

    /**
     * Create an instance of {@link ValidateAccountQuery }
     * 
     */
    public ValidateAccountQuery createValidateAccountQuery() {
        return new ValidateAccountQuery();
    }

    /**
     * Create an instance of {@link CustomerIdByAccountIdQuery }
     * 
     */
    public CustomerIdByAccountIdQuery createCustomerIdByAccountIdQuery() {
        return new CustomerIdByAccountIdQuery();
    }

    /**
     * Create an instance of {@link NinByAccountIdOrPhoneNumberQuery }
     * 
     */
    public NinByAccountIdOrPhoneNumberQuery createNinByAccountIdOrPhoneNumberQuery() {
        return new NinByAccountIdOrPhoneNumberQuery();
    }

    /**
     * Create an instance of {@link ValidatePhoneNumberQuery }
     * 
     */
    public ValidatePhoneNumberQuery createValidatePhoneNumberQuery() {
        return new ValidatePhoneNumberQuery();
    }

    /**
     * Create an instance of {@link ValidateEmailAddressQuery }
     * 
     */
    public ValidateEmailAddressQuery createValidateEmailAddressQuery() {
        return new ValidateEmailAddressQuery();
    }

    /**
     * Create an instance of {@link VoucherDetailQuery }
     * 
     */
    public VoucherDetailQuery createVoucherDetailQuery() {
        return new VoucherDetailQuery();
    }

    /**
     * Create an instance of {@link VoucherDetailResult }
     * 
     */
    public VoucherDetailResult createVoucherDetailResult() {
        return new VoucherDetailResult();
    }

    /**
     * Create an instance of {@link RedemPrepaidStrip }
     * 
     */
    public RedemPrepaidStrip createRedemPrepaidStrip() {
        return new RedemPrepaidStrip();
    }

    /**
     * Create an instance of {@link RedemPrepaidStripResult }
     * 
     */
    public RedemPrepaidStripResult createRedemPrepaidStripResult() {
        return new RedemPrepaidStripResult();
    }

    /**
     * Create an instance of {@link ValidateAccountResult }
     * 
     */
    public ValidateAccountResult createValidateAccountResult() {
        return new ValidateAccountResult();
    }

    /**
     * Create an instance of {@link CustomerIdByAccountIdResult }
     * 
     */
    public CustomerIdByAccountIdResult createCustomerIdByAccountIdResult() {
        return new CustomerIdByAccountIdResult();
    }

    /**
     * Create an instance of {@link NinByAccountIdOrPhoneNumberResult }
     * 
     */
    public NinByAccountIdOrPhoneNumberResult createNinByAccountIdOrPhoneNumberResult() {
        return new NinByAccountIdOrPhoneNumberResult();
    }

    /**
     * Create an instance of {@link ValidatePhoneNumberResult }
     * 
     */
    public ValidatePhoneNumberResult createValidatePhoneNumberResult() {
        return new ValidatePhoneNumberResult();
    }

    /**
     * Create an instance of {@link ValidateEmailAddressResult }
     * 
     */
    public ValidateEmailAddressResult createValidateEmailAddressResult() {
        return new ValidateEmailAddressResult();
    }

    /**
     * Create an instance of {@link BundleCatalogueQuery }
     * 
     */
    public BundleCatalogueQuery createBundleCatalogueQuery() {
        return new BundleCatalogueQuery();
    }

    /**
     * Create an instance of {@link BundleCatalogueResult }
     * 
     */
    public BundleCatalogueResult createBundleCatalogueResult() {
        return new BundleCatalogueResult();
    }

    /**
     * Create an instance of {@link BuyBundle }
     * 
     */
    public BuyBundle createBuyBundle() {
        return new BuyBundle();
    }

    /**
     * Create an instance of {@link BuyBundleResult }
     * 
     */
    public BuyBundleResult createBuyBundleResult() {
        return new BuyBundleResult();
    }

    /**
     * Create an instance of {@link BuyBundleUsingPriceInCentsData }
     * 
     */
    public BuyBundleUsingPriceInCentsData createBuyBundleUsingPriceInCentsData() {
        return new BuyBundleUsingPriceInCentsData();
    }

    /**
     * Create an instance of {@link BuyBundleUsingPriceInCentsResult }
     * 
     */
    public BuyBundleUsingPriceInCentsResult createBuyBundleUsingPriceInCentsResult() {
        return new BuyBundleUsingPriceInCentsResult();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link AddCustomerResult }
     * 
     */
    public AddCustomerResult createAddCustomerResult() {
        return new AddCustomerResult();
    }

    /**
     * Create an instance of {@link ValidateReferenceIdQuery }
     * 
     */
    public ValidateReferenceIdQuery createValidateReferenceIdQuery() {
        return new ValidateReferenceIdQuery();
    }

    /**
     * Create an instance of {@link ValidateReferenceIdResult }
     * 
     */
    public ValidateReferenceIdResult createValidateReferenceIdResult() {
        return new ValidateReferenceIdResult();
    }

    /**
     * Create an instance of {@link TPGWObject }
     * 
     */
    public TPGWObject createTPGWObject() {
        return new TPGWObject();
    }

    /**
     * Create an instance of {@link TPGWContext }
     * 
     */
    public TPGWContext createTPGWContext() {
        return new TPGWContext();
    }

    /**
     * Create an instance of {@link Ucspec }
     * 
     */
    public Ucspec createUcspec() {
        return new Ucspec();
    }

    /**
     * Create an instance of {@link AccountList }
     * 
     */
    public AccountList createAccountList() {
        return new AccountList();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link BundleList }
     * 
     */
    public BundleList createBundleList() {
        return new BundleList();
    }

    /**
     * Create an instance of {@link Bundle }
     * 
     */
    public Bundle createBundle() {
        return new Bundle();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPGWError }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TPGWError }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "TPGWError")
    public JAXBElement<TPGWError> createTPGWError(TPGWError value) {
        return new JAXBElement<TPGWError>(_TPGWError_QNAME, TPGWError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "IsUpRequest")
    public JAXBElement<String> createIsUpRequest(String value) {
        return new JAXBElement<String>(_IsUpRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Done }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Done }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "Done")
    public JAXBElement<Done> createDone(Done value) {
        return new JAXBElement<Done>(_Done_QNAME, Done.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Authenticate }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Authenticate }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "Authenticate")
    public JAXBElement<Authenticate> createAuthenticate(Authenticate value) {
        return new JAXBElement<Authenticate>(_Authenticate_QNAME, Authenticate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticateResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthenticateResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "AuthenticateResult")
    public JAXBElement<AuthenticateResult> createAuthenticateResult(AuthenticateResult value) {
        return new JAXBElement<AuthenticateResult>(_AuthenticateResult_QNAME, AuthenticateResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionStatusQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionStatusQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "TransactionStatusQuery")
    public JAXBElement<TransactionStatusQuery> createTransactionStatusQuery(TransactionStatusQuery value) {
        return new JAXBElement<TransactionStatusQuery>(_TransactionStatusQuery_QNAME, TransactionStatusQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionStatusResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionStatusResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "TransactionStatusResult")
    public JAXBElement<TransactionStatusResult> createTransactionStatusResult(TransactionStatusResult value) {
        return new JAXBElement<TransactionStatusResult>(_TransactionStatusResult_QNAME, TransactionStatusResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BalanceQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BalanceQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BalanceQuery")
    public JAXBElement<BalanceQuery> createBalanceQuery(BalanceQuery value) {
        return new JAXBElement<BalanceQuery>(_BalanceQuery_QNAME, BalanceQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BalanceResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BalanceResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BalanceResult")
    public JAXBElement<BalanceResult> createBalanceResult(BalanceResult value) {
        return new JAXBElement<BalanceResult>(_BalanceResult_QNAME, BalanceResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataBalanceQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataBalanceQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "DataBalanceQuery")
    public JAXBElement<DataBalanceQuery> createDataBalanceQuery(DataBalanceQuery value) {
        return new JAXBElement<DataBalanceQuery>(_DataBalanceQuery_QNAME, DataBalanceQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataBalanceResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataBalanceResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "DataBalanceResult")
    public JAXBElement<DataBalanceResult> createDataBalanceResult(DataBalanceResult value) {
        return new JAXBElement<DataBalanceResult>(_DataBalanceResult_QNAME, DataBalanceResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BalanceTransfer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BalanceTransfer }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BalanceTransfer")
    public JAXBElement<BalanceTransfer> createBalanceTransfer(BalanceTransfer value) {
        return new JAXBElement<BalanceTransfer>(_BalanceTransfer_QNAME, BalanceTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BalanceTransferResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BalanceTransferResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BalanceTransferResult")
    public JAXBElement<BalanceTransferResult> createBalanceTransferResult(BalanceTransferResult value) {
        return new JAXBElement<BalanceTransferResult>(_BalanceTransferResult_QNAME, BalanceTransferResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateAccountQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateAccountQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidateAccountQuery")
    public JAXBElement<ValidateAccountQuery> createValidateAccountQuery(ValidateAccountQuery value) {
        return new JAXBElement<ValidateAccountQuery>(_ValidateAccountQuery_QNAME, ValidateAccountQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerIdByAccountIdQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerIdByAccountIdQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "CustomerIdByAccountIdQuery")
    public JAXBElement<CustomerIdByAccountIdQuery> createCustomerIdByAccountIdQuery(CustomerIdByAccountIdQuery value) {
        return new JAXBElement<CustomerIdByAccountIdQuery>(_CustomerIdByAccountIdQuery_QNAME, CustomerIdByAccountIdQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NinByAccountIdOrPhoneNumberQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NinByAccountIdOrPhoneNumberQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "NinByAccountIdOrPhoneNumberQuery")
    public JAXBElement<NinByAccountIdOrPhoneNumberQuery> createNinByAccountIdOrPhoneNumberQuery(NinByAccountIdOrPhoneNumberQuery value) {
        return new JAXBElement<NinByAccountIdOrPhoneNumberQuery>(_NinByAccountIdOrPhoneNumberQuery_QNAME, NinByAccountIdOrPhoneNumberQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidatePhoneNumberQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidatePhoneNumberQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidatePhoneNumberQuery")
    public JAXBElement<ValidatePhoneNumberQuery> createValidatePhoneNumberQuery(ValidatePhoneNumberQuery value) {
        return new JAXBElement<ValidatePhoneNumberQuery>(_ValidatePhoneNumberQuery_QNAME, ValidatePhoneNumberQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateEmailAddressQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateEmailAddressQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidateEmailAddressQuery")
    public JAXBElement<ValidateEmailAddressQuery> createValidateEmailAddressQuery(ValidateEmailAddressQuery value) {
        return new JAXBElement<ValidateEmailAddressQuery>(_ValidateEmailAddressQuery_QNAME, ValidateEmailAddressQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VoucherDetailQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VoucherDetailQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "VoucherDetailQuery")
    public JAXBElement<VoucherDetailQuery> createVoucherDetailQuery(VoucherDetailQuery value) {
        return new JAXBElement<VoucherDetailQuery>(_VoucherDetailQuery_QNAME, VoucherDetailQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VoucherDetailResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VoucherDetailResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "VoucherDetailResult")
    public JAXBElement<VoucherDetailResult> createVoucherDetailResult(VoucherDetailResult value) {
        return new JAXBElement<VoucherDetailResult>(_VoucherDetailResult_QNAME, VoucherDetailResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RedemPrepaidStrip }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RedemPrepaidStrip }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "RedemPrepaidStrip")
    public JAXBElement<RedemPrepaidStrip> createRedemPrepaidStrip(RedemPrepaidStrip value) {
        return new JAXBElement<RedemPrepaidStrip>(_RedemPrepaidStrip_QNAME, RedemPrepaidStrip.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RedemPrepaidStripResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RedemPrepaidStripResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "RedemPrepaidStripResult")
    public JAXBElement<RedemPrepaidStripResult> createRedemPrepaidStripResult(RedemPrepaidStripResult value) {
        return new JAXBElement<RedemPrepaidStripResult>(_RedemPrepaidStripResult_QNAME, RedemPrepaidStripResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateAccountResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateAccountResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidateAccountResult")
    public JAXBElement<ValidateAccountResult> createValidateAccountResult(ValidateAccountResult value) {
        return new JAXBElement<ValidateAccountResult>(_ValidateAccountResult_QNAME, ValidateAccountResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerIdByAccountIdResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerIdByAccountIdResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "CustomerIdByAccountIdResult")
    public JAXBElement<CustomerIdByAccountIdResult> createCustomerIdByAccountIdResult(CustomerIdByAccountIdResult value) {
        return new JAXBElement<CustomerIdByAccountIdResult>(_CustomerIdByAccountIdResult_QNAME, CustomerIdByAccountIdResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NinByAccountIdOrPhoneNumberResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NinByAccountIdOrPhoneNumberResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "NinByAccountIdOrPhoneNumberResult")
    public JAXBElement<NinByAccountIdOrPhoneNumberResult> createNinByAccountIdOrPhoneNumberResult(NinByAccountIdOrPhoneNumberResult value) {
        return new JAXBElement<NinByAccountIdOrPhoneNumberResult>(_NinByAccountIdOrPhoneNumberResult_QNAME, NinByAccountIdOrPhoneNumberResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidatePhoneNumberResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidatePhoneNumberResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidatePhoneNumberResult")
    public JAXBElement<ValidatePhoneNumberResult> createValidatePhoneNumberResult(ValidatePhoneNumberResult value) {
        return new JAXBElement<ValidatePhoneNumberResult>(_ValidatePhoneNumberResult_QNAME, ValidatePhoneNumberResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateEmailAddressResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateEmailAddressResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidateEmailAddressResult")
    public JAXBElement<ValidateEmailAddressResult> createValidateEmailAddressResult(ValidateEmailAddressResult value) {
        return new JAXBElement<ValidateEmailAddressResult>(_ValidateEmailAddressResult_QNAME, ValidateEmailAddressResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BundleCatalogueQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BundleCatalogueQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BundleCatalogueQuery")
    public JAXBElement<BundleCatalogueQuery> createBundleCatalogueQuery(BundleCatalogueQuery value) {
        return new JAXBElement<BundleCatalogueQuery>(_BundleCatalogueQuery_QNAME, BundleCatalogueQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BundleCatalogueResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BundleCatalogueResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BundleCatalogueResult")
    public JAXBElement<BundleCatalogueResult> createBundleCatalogueResult(BundleCatalogueResult value) {
        return new JAXBElement<BundleCatalogueResult>(_BundleCatalogueResult_QNAME, BundleCatalogueResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuyBundle }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BuyBundle }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BuyBundle")
    public JAXBElement<BuyBundle> createBuyBundle(BuyBundle value) {
        return new JAXBElement<BuyBundle>(_BuyBundle_QNAME, BuyBundle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuyBundleResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BuyBundleResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BuyBundleResult")
    public JAXBElement<BuyBundleResult> createBuyBundleResult(BuyBundleResult value) {
        return new JAXBElement<BuyBundleResult>(_BuyBundleResult_QNAME, BuyBundleResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuyBundleUsingPriceInCentsData }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BuyBundleUsingPriceInCentsData }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BuyBundleUsingPriceInCentsData")
    public JAXBElement<BuyBundleUsingPriceInCentsData> createBuyBundleUsingPriceInCentsData(BuyBundleUsingPriceInCentsData value) {
        return new JAXBElement<BuyBundleUsingPriceInCentsData>(_BuyBundleUsingPriceInCentsData_QNAME, BuyBundleUsingPriceInCentsData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuyBundleUsingPriceInCentsResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BuyBundleUsingPriceInCentsResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "BuyBundleUsingPriceInCentsResult")
    public JAXBElement<BuyBundleUsingPriceInCentsResult> createBuyBundleUsingPriceInCentsResult(BuyBundleUsingPriceInCentsResult value) {
        return new JAXBElement<BuyBundleUsingPriceInCentsResult>(_BuyBundleUsingPriceInCentsResult_QNAME, BuyBundleUsingPriceInCentsResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "NewCustomer")
    public JAXBElement<Customer> createNewCustomer(Customer value) {
        return new JAXBElement<Customer>(_NewCustomer_QNAME, Customer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "Customer")
    public JAXBElement<Customer> createCustomer(Customer value) {
        return new JAXBElement<Customer>(_Customer_QNAME, Customer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddCustomerResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddCustomerResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "AddCustomerResult")
    public JAXBElement<AddCustomerResult> createAddCustomerResult(AddCustomerResult value) {
        return new JAXBElement<AddCustomerResult>(_AddCustomerResult_QNAME, AddCustomerResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateReferenceIdQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateReferenceIdQuery }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidateReferenceIdQuery")
    public JAXBElement<ValidateReferenceIdQuery> createValidateReferenceIdQuery(ValidateReferenceIdQuery value) {
        return new JAXBElement<ValidateReferenceIdQuery>(_ValidateReferenceIdQuery_QNAME, ValidateReferenceIdQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateReferenceIdResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateReferenceIdResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://xml.smilecoms.com/schema/TPGW", name = "ValidateReferenceIdResult")
    public JAXBElement<ValidateReferenceIdResult> createValidateReferenceIdResult(ValidateReferenceIdResult value) {
        return new JAXBElement<ValidateReferenceIdResult>(_ValidateReferenceIdResult_QNAME, ValidateReferenceIdResult.class, null, value);
    }

}
