//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.smilecoms.com/schema/TPGW", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.factorialsystems.msscprovider.wsdl.smile;
