//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for RedemPrepaidStripResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RedemPrepaidStripResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xml.smilecoms.com/schema/TPGW}TPGWObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Status" type="{http://xml.smilecoms.com/schema/TPGW}stDone"/&gt;
 *         &lt;element name="ValueInCents" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="RedemptionAccountId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RedemPrepaidStripResult", propOrder = {
    "status",
    "valueInCents",
    "redemptionAccountId"
})
public class RedemPrepaidStripResult
    extends TPGWObject
{

    @XmlElement(name = "Status", required = true)
    @XmlSchemaType(name = "string")
    protected StDone status;
    @XmlElement(name = "ValueInCents")
    protected double valueInCents;
    @XmlElement(name = "RedemptionAccountId")
    protected long redemptionAccountId;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StDone }
     *     
     */
    public StDone getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StDone }
     *     
     */
    public void setStatus(StDone value) {
        this.status = value;
    }

    /**
     * Gets the value of the valueInCents property.
     * 
     */
    public double getValueInCents() {
        return valueInCents;
    }

    /**
     * Sets the value of the valueInCents property.
     * 
     */
    public void setValueInCents(double value) {
        this.valueInCents = value;
    }

    /**
     * Gets the value of the redemptionAccountId property.
     * 
     */
    public long getRedemptionAccountId() {
        return redemptionAccountId;
    }

    /**
     * Sets the value of the redemptionAccountId property.
     * 
     */
    public void setRedemptionAccountId(long value) {
        this.redemptionAccountId = value;
    }

}
