//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for TPGWObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPGWObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TPGWContext" type="{http://xml.smilecoms.com/schema/TPGW}TPGWContext"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPGWObject", propOrder = {
    "tpgwContext"
})
@XmlSeeAlso({
    TransactionStatusQuery.class,
    TransactionStatusResult.class,
    BalanceQuery.class,
    BalanceResult.class,
    DataBalanceQuery.class,
    DataBalanceResult.class,
    BalanceTransfer.class,
    BalanceTransferResult.class,
    ValidateAccountQuery.class,
    CustomerIdByAccountIdQuery.class,
    NinByAccountIdOrPhoneNumberQuery.class,
    ValidatePhoneNumberQuery.class,
    ValidateEmailAddressQuery.class,
    VoucherDetailQuery.class,
    VoucherDetailResult.class,
    RedemPrepaidStrip.class,
    RedemPrepaidStripResult.class,
    ValidateAccountResult.class,
    CustomerIdByAccountIdResult.class,
    NinByAccountIdOrPhoneNumberResult.class,
    ValidatePhoneNumberResult.class,
    ValidateEmailAddressResult.class,
    BundleCatalogueQuery.class,
    BundleCatalogueResult.class,
    BuyBundle.class,
    BuyBundleResult.class,
    BuyBundleUsingPriceInCentsData.class,
    BuyBundleUsingPriceInCentsResult.class,
    Customer.class,
    AddCustomerResult.class,
    ValidateReferenceIdQuery.class,
    ValidateReferenceIdResult.class,
    Bundle.class
})
public class TPGWObject {

    @XmlElement(name = "TPGWContext", required = true)
    protected TPGWContext tpgwContext;

    /**
     * Gets the value of the tpgwContext property.
     * 
     * @return
     *     possible object is
     *     {@link TPGWContext }
     *     
     */
    public TPGWContext getTPGWContext() {
        return tpgwContext;
    }

    /**
     * Sets the value of the tpgwContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPGWContext }
     *     
     */
    public void setTPGWContext(TPGWContext value) {
        this.tpgwContext = value;
    }

}
