//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TransactionStatusQuery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionStatusQuery"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xml.smilecoms.com/schema/TPGW}TPGWObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UniqueTransactionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SearchStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="SearchEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionStatusQuery", propOrder = {
    "uniqueTransactionId",
    "searchStartDate",
    "searchEndDate"
})
public class TransactionStatusQuery
    extends TPGWObject
{

    @XmlElement(name = "UniqueTransactionId", required = true)
    protected String uniqueTransactionId;
    @XmlElement(name = "SearchStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar searchStartDate;
    @XmlElement(name = "SearchEndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar searchEndDate;

    /**
     * Gets the value of the uniqueTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueTransactionId() {
        return uniqueTransactionId;
    }

    /**
     * Sets the value of the uniqueTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueTransactionId(String value) {
        this.uniqueTransactionId = value;
    }

    /**
     * Gets the value of the searchStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSearchStartDate() {
        return searchStartDate;
    }

    /**
     * Sets the value of the searchStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSearchStartDate(XMLGregorianCalendar value) {
        this.searchStartDate = value;
    }

    /**
     * Gets the value of the searchEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSearchEndDate() {
        return searchEndDate;
    }

    /**
     * Sets the value of the searchEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSearchEndDate(XMLGregorianCalendar value) {
        this.searchEndDate = value;
    }

}
