//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.15 at 06:01:37 PM WAT 
//


package io.factorialsystems.msscprovider.wsdl.smile;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VoucherDetailResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoucherDetailResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xml.smilecoms.com/schema/TPGW}TPGWObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PrepaidStripId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ValueInCents" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RedemptionAccountId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="RedemptionAccountHistoryId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="GeneratedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="InvoiceData" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UnitCreditSpecificationId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AccountId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="PIN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoucherDetailResult", propOrder = {
    "prepaidStripId",
    "valueInCents",
    "status",
    "redemptionAccountId",
    "redemptionAccountHistoryId",
    "generatedDate",
    "expiryDate",
    "invoiceData",
    "unitCreditSpecificationId",
    "accountId",
    "pin"
})
public class VoucherDetailResult
    extends TPGWObject
{

    @XmlElement(name = "PrepaidStripId")
    protected int prepaidStripId;
    @XmlElement(name = "ValueInCents")
    protected double valueInCents;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "RedemptionAccountId")
    protected long redemptionAccountId;
    @XmlElement(name = "RedemptionAccountHistoryId")
    protected long redemptionAccountHistoryId;
    @XmlElement(name = "GeneratedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar generatedDate;
    @XmlElement(name = "ExpiryDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "InvoiceData", required = true)
    protected String invoiceData;
    @XmlElement(name = "UnitCreditSpecificationId")
    protected int unitCreditSpecificationId;
    @XmlElement(name = "AccountId")
    protected long accountId;
    @XmlElement(name = "PIN", required = true)
    protected String pin;

    /**
     * Gets the value of the prepaidStripId property.
     * 
     */
    public int getPrepaidStripId() {
        return prepaidStripId;
    }

    /**
     * Sets the value of the prepaidStripId property.
     * 
     */
    public void setPrepaidStripId(int value) {
        this.prepaidStripId = value;
    }

    /**
     * Gets the value of the valueInCents property.
     * 
     */
    public double getValueInCents() {
        return valueInCents;
    }

    /**
     * Sets the value of the valueInCents property.
     * 
     */
    public void setValueInCents(double value) {
        this.valueInCents = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the redemptionAccountId property.
     * 
     */
    public long getRedemptionAccountId() {
        return redemptionAccountId;
    }

    /**
     * Sets the value of the redemptionAccountId property.
     * 
     */
    public void setRedemptionAccountId(long value) {
        this.redemptionAccountId = value;
    }

    /**
     * Gets the value of the redemptionAccountHistoryId property.
     * 
     */
    public long getRedemptionAccountHistoryId() {
        return redemptionAccountHistoryId;
    }

    /**
     * Sets the value of the redemptionAccountHistoryId property.
     * 
     */
    public void setRedemptionAccountHistoryId(long value) {
        this.redemptionAccountHistoryId = value;
    }

    /**
     * Gets the value of the generatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGeneratedDate() {
        return generatedDate;
    }

    /**
     * Sets the value of the generatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGeneratedDate(XMLGregorianCalendar value) {
        this.generatedDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the invoiceData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceData() {
        return invoiceData;
    }

    /**
     * Sets the value of the invoiceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceData(String value) {
        this.invoiceData = value;
    }

    /**
     * Gets the value of the unitCreditSpecificationId property.
     * 
     */
    public int getUnitCreditSpecificationId() {
        return unitCreditSpecificationId;
    }

    /**
     * Sets the value of the unitCreditSpecificationId property.
     * 
     */
    public void setUnitCreditSpecificationId(int value) {
        this.unitCreditSpecificationId = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     */
    public long getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     */
    public void setAccountId(long value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIN() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIN(String value) {
        this.pin = value;
    }

}
