//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.19 at 01:39:42 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.convergenceondemand.net/TMP/")
package io.factorialsystems.msscprovider.wsdl;
